<a href="https://colab.research.google.com/github/leeet1004835/colab/blob/main/0416.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0416 data analysis

In [1]:
import numpy as np

In [3]:
print(np.__version__) # 屬性檢查版本號
print(np.__file__) #  屬性檢查安裝路徑

2.0.2
/usr/local/lib/python3.12/dist-packages/numpy/__init__.py

In [10]:
# 從 list 創造 ndarray
prime_list = [2, 3, 5, 7, 11]
print(prime_list)
print(type(prime_list))

prime_array = np.array(prime_list)
print(prime_array)
print(type(prime_array))

[2, 3, 5, 7, 11]
<class 'list'>
[ 2  3  5  7 11]
<class 'numpy.ndarray'>

In [14]:
print(prime_list + prime_list) # concatenation
print(prime_list * 3) # duplicate/extend

print(prime_array + prime_array) # element-wise add
print(prime_array * 3) # element-wise multiply
print(prime_array ** 2) # element-wise power

[2, 3, 5, 7, 11, 2, 3, 5, 7, 11]
[2, 3, 5, 7, 11, 2, 3, 5, 7, 11, 2, 3, 5, 7, 11]
[ 4  6 10 14 22]
[ 6  9 15 21 33]
[  4   9  25  49 121]

In [20]:
'''
利用 NumPy 函數創造內容元素相同的 ndarray
np.zeros()
np.ones()
np.full()
'''
print(np.zeros(5, dtype = int)) # dtype = data type
print(np.ones(5, dtype = int))
print(np.ones(10, dtype = int) * 5566)
print(np.full(10, 5566, dtype = int))

[0 0 0 0 0]
[1 1 1 1 1]
[5566 5566 5566 5566 5566 5566 5566 5566 5566 5566]
[5566 5566 5566 5566 5566 5566 5566 5566 5566 5566]

In [28]:
'''
利用 NumPy 函數創造數列型態的 ndarray
np.arange(start, stop, step)
np.linspace(start, stop, num)值得注意的是stop參數預設為包含。
'''
print(np.arange(1, 11, 2))
print(np.linspace(1, 100, 10, dtype = int)) # 固定間距的數列

[1 3 5 7 9]
[  1  12  23  34  45  56  67  78  89 100]

In [37]:
# 可內積(dot)的
# (m, n) dot (i, j), n == i
arr_1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
arr_2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(arr_1.shape)
print(arr_2.T.shape)
np.dot(arr_1, arr_2.T)
print(len(arr_1.shape))
print(arr_1.ndim)

(3, 2)
(2, 3)
2
2

In [38]:
'''
常用的 ndarray 屬性:
ndarray.ndim 維度數。
ndarray.shape 外型。
ndarray.size 元素個數。
ndarray.dtype 資料類別。
'''
prime_list = [2, 3, 5, 7, 11]
prime_array = np.array(prime_list)
print(prime_array)
print(prime_array.ndim)
print(prime_array.shape)
print(prime_array.size)
print(prime_array.dtype)

[ 2  3  5  7 11]
1
(5,)
5
int64

In [49]:
'''
零維 ndarray: 純量
一維 ndarray: 向量
二維 ndarray: 矩陣
三維或者n維 ndarray: 張量
'''
an_integer = 5566
print(an_integer)

scalar = np.array(an_integer)
print(scalar)
print(scalar.shape)
print(scalar.ndim)

vector = np.array([5, 5, 6, 6])
print(vector)
print(vector.shape) # 四個元素
print(vector.ndim) # 維度是1

matrix = np.array([
    [5, 5],
    [6, 6]
])
print(matrix)
print(matrix.shape) # (m, n)，2 rows, 4 columns
print(matrix.ndim) # 維度是2

tensor = np.array([
    [
        [5, 5],
        [6, 6]
    ],
    [
        [5, 5],
        [6, 6]
    ],
    [
        [5, 5],
        [6, 6]
    ]
])
print(tensor)
print(tensor.shape) # (l, m, n)
print(tensor.ndim) # 維度是3

5566
5566
()
0
[5 5 6 6]
(4,)
1
[[5 5]
 [6 6]]
(2, 2)
2
[[[5 5]
  [6 6]]

 [[5 5]
  [6 6]]

 [[5 5]
  [6 6]]]
(3, 2, 2)
3

In [54]:
print(prime_list)
print(prime_array)

print(prime_array[0])
print(prime_array[1])
print(prime_array[2])
print(prime_array[3])
print(prime_array[4])

print(prime_array[-1])
print(prime_array[-2])
print(prime_array[-3])
print(prime_array[-4])
print(prime_array[-5])

print(prime_array[::])
print(prime_array[:2])
print(prime_array[2:])

[2, 3, 5, 7, 11]
[ 2  3  5  7 11]
2
3
5
7
11
11
7
5
3
2
[ 2  3  5  7 11]
[2 3]
[ 5  7 11]

In [60]:
# ndarray 與 list 相異的地方
matrix_by_list = [[5, 5],
                  [6, 6],
                  [55, 66]]
matrix = np.array([[5, 5],
                  [6, 6],
                  [55, 66]])
print(matrix_by_list)
print(matrix)

print(matrix_by_list[2][1])
print(matrix[2, 1]) # 取第二列第一欄

print(matrix_by_list[0][1], matrix_by_list[1][1], matrix_by_list[2][1])
print(matrix[:, 1]) # 取所有列的第一欄
print(matrix[:, [1]]) # 取所有列的第一欄，但不降維

[[5, 5], [6, 6], [55, 66]]
[[ 5  5]
 [ 6  6]
 [55 66]]
66
66
5 6 66
[ 5  6 66]
[[ 5]
 [ 6]
 [66]]

In [66]:
# 同質性資料結構類別，若資料維不同型別，會進行資料型別同質性轉換
mixed_type_list = [False, True, 55, 66, 3.14, "Hello world!"]
homogeneous_array = np.array([False, True, 55, 66, 3.14, "Hello world!"])
for elem in mixed_type_list:
  print(type(elem))

<class 'bool'>
<class 'bool'>
<class 'int'>
<class 'int'>
<class 'float'>
<class 'str'>

In [67]:
print(homogeneous_array)
for elem in homogeneous_array:
  print(type(elem))

['False' 'True' '55' '66' '3.14' 'Hello world!']
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>

In [77]:
'''
支援特殊的 indexing 語法
Fancy indexing
Boolean indexing
'''
print(prime_list)
print(prime_list[::2])

print(prime_array)
print(prime_array[[0, 1, -1]]) # Fancy indexing，可以更有彈性地取出 ndarray 元素
print(prime_array[[True, True, False, False, True]]) # Boolean indexing

[2, 3, 5, 7, 11]
[2, 5, 11]
[ 2  3  5  7 11]
[ 2  3 11]
[ 2  3 11]

In [80]:
interger_array = np.arange(1, 100)
print(interger_array)

interger_array[interger_array % 2 == 0] # 等同於下面兩行程式
# bool_indexing = interger_array % 2 == 0
# interger_array[bool_indexing]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [87]:
'''
常用的 ndarray 操作:
調整外型。
複製。
合併。
分割。
'''
print(matrix)
print(matrix.ravel()) # 直接回到1維
print(tensor)
print(tensor.ravel()) # 直接回到1維

[[ 5  5]
 [ 6  6]
 [55 66]]
[ 5  5  6  6 55 66]
[[[5 5]
  [6 6]]

 [[5 5]
  [6 6]]

 [[5 5]
  [6 6]]]
[5 5 6 6 5 5 6 6 5 5 6 6]

In [95]:
arr = np.arange(100)

print(arr.shape)
print(arr.reshape(25, 4))
print(arr.reshape(5, 5, 4))

(100,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]
 [72 73 74 75]
 [76 77 78 79]
 [80 81 82 83]
 [84 85 86 87]
 [88 89 90 91]
 [92 93 94 95]
 [96 97 98 99]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]
  [72 73 74 75]
  [76 77 78 79]]

 [[80 81 82 83]
  [84 85 86 87]
  [88 89 90 91]
  [92 93 94 95]
  [96 97 98 99]]]

In [97]:
print(arr.reshape(5, -1)) # 在其他維度已經決定時可以方便地指定 -1 給最後一個維度
print(arr.reshape(-1, 5))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

In [100]:
arr = np.arange(10)
mat = arr.reshape(-1, 2) # mat is a view of arr
print(arr)
print(mat)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

In [102]:
arr[-1] = 999
print(arr)
print(mat)

[  0   1   2   3   4   5   6   7   8 999]
[[  0   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8 999]]

In [107]:
'''
合併
使用 np.concatenate() 函數合併
指定參數 axis = 0 垂直合併 (預設值)
指定參數 axis = 1 水平合併
'''
x1 = np.arange(1, 11).reshape(-1, 1)
print(x1)
x0 = np.ones(x1.size).reshape(-1, 1)
print(x0)

# y = error(residual) + w1x1 + ... + wnxn
# y = error*1 + w1*x1 + ... + wn*xn
# y = w0*x0 + w1*x1 + ... + wn*xn

x = np.concatenate((x0, x1), axis = 1) # 水平合併
print(x)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]

In [118]:
'''
分割
使用 np.split()函數分割
指定參數 axis = 0 垂直分割 (預設值)
指定參數 axis = 1 水平分割
'''
x
np.split(x, [2], axis = 0)

[array([[1., 1.],
        [1., 2.]]),
 array([[ 1.,  3.],
        [ 1.,  4.],
        [ 1.,  5.],
        [ 1.,  6.],
        [ 1.,  7.],
        [ 1.,  8.],
        [ 1.,  9.],
        [ 1., 10.]])]

In [171]:
array_range = np.arange(20).reshape(-1, 2)
print(array_range)
upper_array, lower_array = np.split(array_range, [2], axis = 0)
print(upper_array)
print(lower_array)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[0 1]
 [2 3]]
[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

In [125]:
valid_percentage = 0.2
valid_index = int(x.shape[0] * valid_percentage)
print(valid_index)

train_percentage = 0.7
train_index = int(x.shape[0] * train_percentage)
print(train_index)

valid_set, train_set, test_set = np.split(np.arange(x.shape[0]), [valid_index, train_index])
print(valid_set)
print(train_set)
print(test_set)

2
7
[0 1]
[2 3 4 5 6]
[7 8 9]

In [137]:
import numpy as np
import pandas as pd
print(pd.__version__) # 屬性檢查版本號
print(pd.__file__) #  屬性檢查安裝路徑

2.2.2
/usr/local/lib/python3.12/dist-packages/pandas/__init__.py

In [140]:
months_array = np.arange(1, 13)

months_abbreviation = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN",
                       "JLY", "AUG", "SEP", "OCT", "NOV", "DEC"]
months_series = pd.Series(months_array, index = months_abbreviation)
months_series

JAN     1
FEB     2
MAR     3
APR     4
MAY     5
JUN     6
JLY     7
AUG     8
SEP     9
OCT    10
NOV    11
DEC    12
dtype: int64

In [165]:
!wget -Nq https://raw.githubusercontent.com/sergulaydore/metric-learning/master/metric-learning/data/1-dblp-acm/sources.csv
# url = "https://raw.githubusercontent.com/sergulaydore/metric-learning/master/metric-learning/data/1-dblp-acm/sources.csv"

In [164]:
sources = pd.read_csv("sources.csv", encoding='latin1')
# sources = pd.read_csv(url, encoding='latin1')
sources.head()

,id,title,authors,venue,year
0,journals/sigmod/Mackay99,Semantic Integration of Environmental Models f...,D. Scott Mackay,SIGMOD Record,1999
1,conf/vldb/PoosalaI96,Estimation of Query-Result Distribution and it...,"Viswanath Poosala, Yannis E. Ioannidis",VLDB,1996
2,conf/vldb/PalpanasSCP02,Incremental Maintenance for Non-Distributive A...,"Themistoklis Palpanas, Richard Sidle, Hamid Pi...",VLDB,2002
3,conf/vldb/GardarinGT96,Cost-based Selection of Path Expression Proces...,"Zhao-Hui Tang, Georges Gardarin, Jean-Robert G...",VLDB,1996
4,conf/vldb/HoelS95,Benchmarking Spatial Join Operations with Spat...,"Erik G. Hoel, Hanan Samet",VLDB,1995

In [166]:
sources.loc[[6, 9, 13], :]

,id,title,authors,venue,year
6,journals/sigmod/Ouksel02,Mining the World Wide Web: An Information Sear...,Aris M. Ouksel,SIGMOD Record,2002
9,journals/sigmod/DAndreaJ96,UniSQL's Next-Generation Object-Relational Dat...,"Phil Janus, Albert D'Andrea",SIGMOD Record,1996
13,journals/vldb/SheikholeslamiCZ00,WaveCluster: A Wavelet Based Clustering Approa...,"Surojit Chatterjee, Gholamhosein Sheikholeslam...",VLDB J.,2000

In [174]:
sources[sources["authors"].str.contains("Aris M. Ouksel")]

,id,title,authors,venue,year
6,journals/sigmod/Ouksel02,Mining the World Wide Web: An Information Sear...,Aris M. Ouksel,SIGMOD Record,2002
266,journals/sigmod/OukselS99,Semantic Interoperability in Global Informatio...,"Amit P. Sheth, Aris M. Ouksel",SIGMOD Record,1999
2073,journals/sigmod/Ouksel03,In-context peer-to-peer information filtering ...,Aris M. Ouksel,SIGMOD Record,2003

In [175]:
condition_1 = sources["title"] == "Estimation of Query-Result Distribution and its Application in Parallel-Join Load Balancing"
condition_2 = sources["title"] == "Enhanced Abstract Data Types in Object-Relational Databases"
condition_3 = sources["title"] == "Free Parallel Data Mining"
condition_union = condition_1 | condition_2 | condition_3
sources[condition_union]

,id,title,authors,venue,year
1,conf/vldb/PoosalaI96,Estimation of Query-Result Distribution and it...,"Viswanath Poosala, Yannis E. Ioannidis",VLDB,1996
7,journals/vldb/Seshadri98,Enhanced Abstract Data Types in Object-Relatio...,Praveen Seshadri,VLDB J.,1998
24,conf/sigmod/LiS98,Free Parallel Data Mining,"Bin Li, Dennis Shasha",SIGMOD Conference,1998

In [181]:
sources.sort_values("year", ascending = False)

,id,title,authors,venue,year
2584,conf/vldb/SchindlerAG03,Lachesis: Robust Database Storage Management B...,"Anastassia Ailamaki, Jiri Schindler, Gregory R...",VLDB,2003
36,conf/vldb/HristidisGP03,Efficient IR-Style Keyword Search over Relatio...,"Yannis Papakonstantinou, Luis Gravano, Vagelis...",VLDB,2003
11,conf/sigmod/AbadiCCCCEGHMRSSTXYZ03,Aurora: A Data Stream Management System,"Nesime Tatbul, Daniel J. Abadi, C. Erwin, Anur...",SIGMOD Conference,2003
33,conf/vldb/ZhouS03,Data Bubbles for Non-Vector Data: Speeding-up ...,"Jörg Sander, Jianjun Zhou",VLDB,2003
1686,journals/vldb/AbadiCCCCLSTZ03,Aurora: a new model and architecture for data ...,"Christian Convey, Sangdon Lee, Ugur Çetintemel...",VLDB J.,2003
...,...,...,...,...,...
967,conf/vldb/Lesk94,Experiments on Access to Digital Libraries: Ho...,Michael Lesk,VLDB,1994
96,journals/sigmod/Alonso94b,Trade Press News - Announcement and Preface,Rafael Alonso,SIGMOD Record,1994
99,conf/vldb/PoulovassilisS94,Investigation of Algebraic Query Optimisation ...,"Alexandra Poulovassilis, Carol Small",VLDB,1994
78,conf/sigmod/TheodoulidisAACKS94,The ORES Temporal Database Management System,"Babis Theodoulidis, George Karvelis, Jayant Ch...",SIGMOD Conference,1994
1718,conf/sigmod/Cattell94,ODMG-93: A Standard for Object-Oriented DBMSs,R. G. G. Cattell,SIGMOD Conference,1994